# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run nn_strategy every day

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: qdata
      url: https://github.com
    timeout-minutes: 480
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: update nn strategy
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_IP: ${{ secrets.MYSQL_IP }}
        run: |
          MYSQL_USER=$MYSQL_USER MYSQL_PORT=$MYSQL_PORT MYSQL_PASSWORD=$MYSQL_PASSWORD MYSQL_IP=$MYSQL_IP python src/qtrade/rank_strategy.py
